print ("La pc vale $1500000")
p=int(1500000)
print("==========================")
print("")
print("pero hoy por ser tú, tienes un descuento del 15%")
print("==========================")
print("")
d=float(0.15)
dt=float(p*d)
print(f"Tu descuento es de{dt}")
print("==========================")
print("")
t=float(p-dt)
print(f"El valor total de la pc es: {t}")
