print ("Hola, ingresa un numuero")
a = float(input())
print ("Hola, ingresa otro numuero")
b = float(input())

print ("SUMA")
print ("_____")
print (F"a+b={a+b}")
print ("_____")
print ("")

print ("RESTA")
print ("_____")
print (F"a-b={a-b}")
print ("_____")
print ("")

print ("MULTIPLICACION")
print ("_____")
print (F"a*b={a*b}")
print ("_____")
print ("")

print ("DIVISION")
print ("_____")
print (F"a/b{a/b}")
print (f"El residuo de a/b es: {a%b}")
print ("_____")
print ("")
